VERSION="1.0"

ACCOUNTS=[
"GD6SG4I5UZBQ5ZALOUXIE3LXH64D4RUON4ETXUJDF46757JELOXA7NZM",
"GBP2LLFEZQO4IN4Q72QMZB2V5IHC34PGKMTDSAN26QP2QOLCCYXF6QEX",
]

[DOCUMENTATION]
ORG_NAME="Exness Official(bron to trade)"
ORG_URL="https://exness-official.netlify.app"
ORG_LOGO="https://etuvkcx.stripocdn.email/content/guids/CABINET_71b6881825cf74a182c183d559f18ceff5c4dc526c34d66c49282269e2ff57b5/images/exnesslogo.png"

[[CURRENCIES]]
code="Exness"
issuer="GD6SG4I5UZBQ5ZALOUXIE3LXH64D4RUON4ETXUJDF46757JELOXA7NZM"
display_decimals=7
desc="Exness is a fast, secure, and decentralized digital asset on Stellar, designed for seamless global transactions and real-world utility."
name="Exness Official"
status="live"
image="https://etuvkcx.stripocdn.email/content/guids/CABINET_71b6881825cf74a182c183d559f18ceff5c4dc526c34d66c49282269e2ff57b5/images/exnesslogo.png"
