[[CURRENCIES]]
code = "Sadiya"  # Replace with your asset code
issuer = "GDFLCWAO3IZGDYRQUHU5OIIYGUSEOYFCMLE4EBRTGGXMWB2QK2ZROXWY"  # Replace with your asset's issuing account public key
status = "active"
display_decimals = 2
name = "Sadiya Khanki"  # Replace with your asset name
desc = "Sadiya is a khanki Magiiiii"  # Replace with a short description
image = "https://raw.githubusercontent.com/ituhin721/stellar-asset/refs/heads/main/logo.png"  # Replace with the copied logo URL
