# Stellar Asset Configuration
# Configuration for the "Sadiya" asset

[stellar]
NETWORK_PASSPHRASE = "Public Global Stellar Network ; September 2015"

[[CURRENCIES]]
code = "Sadiya"
issuer = "GDFLCWAO3IZGDYRQUHU5OIIYGUSEOYFCMLE4EBRTGGXMWB2QK2ZROXWY"
home_domain = "peradox.netlify.app"
status = "live"
display_decimals = 2
name = "Sadiya Khanki"
desc = "Sadiya is a khanki Magiiiii"
image = "https://peradox.netlify.app/logo.png"

[[CURRENCIES]]
code = "XLM"
issuer = ""
status = "live"
display_decimals = 7
name = "Lumens"
desc = "The native asset of the Stellar Network"
image = "https://www.stellar.org/wp-content/uploads/2021/02/Stellar_Logo_Full_RGB-1.png"



[NETWORKS]
MAINNET = "Mainnet"
